version: '3'
services:
  app:
    image: jee-app-tomcat
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - db  # The app waits for MySQL to be ready
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/paincare
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: paincare
    ports:
      - "3306:3306"
